name: CI-SCAN
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter codigo
        uses: actions/checkout@v4
      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construindo e Enviando Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags:        
            edsonrsjr/fake-shop:latest, edsonrsjr/fake-shop:v${{ github.run_number }}
  scan:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
    - uses: actions/checkout@v3
    - name: Scan container image with Tenable Cloud Security
      uses: tenable/cloud-security-actions/container-image/scan@v1
      with:
        api-token: ${{ secrets.TENABLE_API_TOKEN }}
        api-url: https://us.app.ermetic.com
        name: edsonrsjr/fake-shop:v${{ github.run_number }}
        fail-on-min-severity: high
